## * Aula Prática 01 - Tipos de Frequência - Python para Usuários de R
## * Curso Comunidade Estatística

In [1]:
import numpy as np
import pandas as pd

# Gerar dados utilizando a biblioteca numpy
        

In [2]:
idade = np.array([10,10,10,10,30,30,30,30,30,30,30,30,50,50,50,50,70,70,70,90])
idade

array([10, 10, 10, 10, 30, 30, 30, 30, 30, 30, 30, 30, 50, 50, 50, 50, 70,
       70, 70, 90])

# Tipo de classe

In [3]:
idade.dtype

dtype('int32')

In [4]:
# ou

In [5]:
idade_rep = np.concatenate([np.repeat(10,4), np.repeat(30,8), np.repeat(50,4), np.repeat(70,3), np.repeat(90,1)])
idade_rep

array([10, 10, 10, 10, 30, 30, 30, 30, 30, 30, 30, 30, 50, 50, 50, 50, 70,
       70, 70, 90])

In [6]:
#ou

In [7]:
idade_rep = np.repeat(np.array([10,30,50,70,90]), repeats = [4,8,4,3,1], axis = 0)
idade_rep

array([10, 10, 10, 10, 30, 30, 30, 30, 30, 30, 30, 30, 50, 50, 50, 50, 70,
       70, 70, 90])

# Verificando se idade é igual idade_rep

In [8]:
idade == idade_rep

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

# Transformar em tabela (DataFrame)

In [9]:
table = pd.DataFrame(idade, columns=["idade"])
table

idade
0      10
1      10
2      10
3      10
4      30
5      30
6      30
7      30
8      30
9      30
10     30
11     30
12     50
13     50
14     50
15     50
16     70
17     70
18     70
19     90

In [10]:
table.value_counts()

idade
30       8
50       4
10       4
70       3
90       1
dtype: int64

# Calculando a frequência simples

In [11]:
table.groupby(['idade']).size()

idade
10    4
30    8
50    4
70    3
90    1
dtype: int64

# Calculando a quantidade de alunos

In [12]:
table.groupby(['idade']).size().sum()

20

In [13]:
table_subset = pd.DataFrame(table.groupby(['idade']).size().cumsum())
table_subset

0
idade    
10      4
30     12
50     16
70     19
90     20

# Adicionando colunas de frequência

# Frequencia Acumulada

In [28]:
#table['Freq_acumulada'] = table['Freq'].cumsum()
table_subset['Freq_acumulada'] = table.groupby(['idade']).size().cumsum()
table_subset


0  Freq_acumulada
idade                    
10      4               4
30     12              12
50     16              16
70     19              19
90     20              20

# Frequência Relativa Simples

In [33]:
table_subset['Freq_relativa_simples'] = table.groupby(['idade']).size().cumsum()/table_subset['Freq_acumulada'].sum()
table_subset

0  Freq_acumulada  Freq_relativa_simples
idade                                           
10      4               4               0.056338
30     12              12               0.169014
50     16              16               0.225352
70     19              19               0.267606
90     20              20               0.281690

In [34]:
table_subset['Freq_relativa_acumulada'] = table_subset['Freq_relativa_simples'].cumsum()
table_subset

0  Freq_acumulada  Freq_relativa_simples  Freq_relativa_acumulada
idade                                                                    
10      4               4               0.056338                 0.056338
30     12              12               0.169014                 0.225352
50     16              16               0.225352                 0.450704
70     19              19               0.267606                 0.718310
90     20              20               0.281690                 1.000000

In [35]:
print(table_subset.head())

        0  Freq_acumulada  Freq_relativa_simples  Freq_relativa_acumulada
idade                                                                    
10      4               4               0.056338                 0.056338
30     12              12               0.169014                 0.225352
50     16              16               0.225352                 0.450704
70     19              19               0.267606                 0.718310
90     20              20               0.281690                 1.000000
